/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:15d13c4e-134a-47fa-a6f2-964a0c9659de",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Cn8iMLdpZ",
    "aws_user_pools_web_client_id": "71n75tehhnvk0d6niqc0e4lpfp",
    "oauth": {},
    "aws_user_files_s3_bucket": "repositorioitz171848-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://beadd2jlfbeavjc43edl637q4e.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-saepa7yxgzb3lhjp4xn4etvxpm"
};


export default awsmobile;
